INSERT INTO tbl_m_bkimia (kode_bkimia, nama_bkimia, deskripsi_bkimia)
VALUE (UUID(),'Kupri (II) Sulfat (PA)', 'Irritant, Dermal Sensitizer, Acute Toxicity (Harmful), Environmental Toxicity'),
(UUID(),'L(+)-Weinsaure (PA)', 'Corrosives'),
(UUID(),'Magnesium Gepulvert (PA)', 'Flammables, Self Heating, Emits Flammable Gas'),
(UUID(),'Magnesium Gepulvert (Teknis)', 'Flammables, Self Heating, Emits Flammable Gas'),
(UUID(),'Mangan (II) - Chlorid-2-Hydrat (PA)', 'Acute Toxicity (Severe), Specific Target Organ'),
(UUID(),'Mangan (IV) - Oxid (PA)', 'Systemic Toxicity (STOST), Environmental Toxicity'),
(UUID(),'Metanol (Teknis)', 'Specific Target Organ Systemic Toxicity (STOST), Acute Toxicity (Harmful)'),
(UUID(),'Methyl Paraben (Teknis)', 'Flammables, Acute Toxicity (Severe), Specific Target Organ Systemic Toxicity (STOST)'),
(UUID(),'Metil Orange (PA)', 'Irritant'),
(UUID(),'Metil Violet (PA)', 'Acute Toxicity (Severe)'),
(UUID(),'NaOH (Teknis)', 'Carcinogen, Corrosives, Irritant, Environmental Toxicity '),
(UUID(),'Napthalin (PA)', 'Corrosives'),
(UUID(),'Natrium  Hydrogen Phospat (PA)', 'Flammables, Carcinogen, Acute Toxicity (Harmful), Environmental Toxicity'),
(UUID(),'Natrium Benzoat (Teknis)', 'Non B3'),
(UUID(),'Natrium Bismutat (PA)', 'Irritant'),
(UUID(),'Natrium Carbonat ( PA )', 'Irritant, Dermal Sensitizer, Acute Toxicity (Harmful)'),
(UUID(),'Nitrophenol ', 'Irritant'),
(UUID(),'Oxalic Acid (Teknis)', 'Respiratory Sensitizer, Specific Target Organ Systemic Toxicity (STOST), Irritant, Dermal Sensitizer, Acute Toxicity (Harmful)'),
(UUID(),'Phenantrholine', 'Corrosives, Irritant, Dermal Sensitizer, Acute Toxicity (Harmful)'),
(UUID(),'Phenol ', 'Acute Toxicity (Severe), Environmental Toxicity'),
(UUID(),'Phenolphatalein (PA)', 'Acute Toxicity (Severe), Respiratory Sensitizer, Specific Target Organ Systemic Toxicity (STOST), Mutagenicity, Corrosives,  Environmental Toxicity'),
(UUID(),'PK (KMNO4) (Teknis)', 'Carcinogen, Reproductive, Mutagenicity, Irritant, Dermal Sensitizer'),
(UUID(),'Potasium Iodate (PA)', 'Oxidizers, Organic Peroxides, Carcinogen, Respiratory Sensitizer, Reproductive, Specific Target Organ Systemic Toxicity (STOST), Mutagenicity, Corrosives, Irritant, Dermal Sensitizer, Acute Toxicity (Harmful), Environmental TUUID(),oxicity'),
(UUID(),'Potasium Permanganat (Teknis)', 'Oxidizers, Organic Peroxides, Corrosives, Irritant, Dermal Sensitizer, Acute Toxicity (Harmful)'),
(UUID(),'Potassium Chromat (PA)', 'Oxidizers, Organic Peroxides, Carcinogen, Respiratory Sensitizer, Reproductive, Specific Target Organ Systemic Toxicity (STOST), Mutagenicity, Corrosives, Irritant, Dermal Sensitizer, Acute Toxicity (Harmful), Environmental TUUID(),oxicity'),
(UUID(),'Potassium Dichromat', 'Carcinogen, Respiratory Sensitizer, Mutagenicity, Acute Toxicity (Severe), Environmental Toxicity '),
(UUID(),'Potassium Hydroxide (Teknis)', 'Corrosives'),
(UUID(),'Potassium Iodide (Teknis)', '-'),
(UUID(),'Potassium Jodida (PA)', 'Specific Target Organ Systemic Toxicity (STOST)'),
(UUID(),'Quecysllber (II)-Jodid', '-'),
(UUID(),'Selekreationgemisch (PA)', '-'),
(UUID(),'Selenium Reagen Merck ', 'Environmental Toxicity'),
(UUID(),'Sodium Hydroxide (PA)', 'Corrosives'),
(UUID(),'Sodium Hydroxide (Teknis)', 'Corrosives'),
(UUID(),'Sodium Tetraborate (Teknis)', 'Reproductive, Irritant'),
(UUID(),'Sulfanic Acid (PA)', 'Corrosives'),
(UUID(),'Sulfanilic Acid (PA)', 'Irritant, Dermal Sensitizer, Acute Toxicity (Harmful)'),
(UUID(),'Tawas (Teknis)', 'Corrosives'),
(UUID(),'Terpentin (Teknis)', 'Irritant, Dermal Sensitizer, Acute Toxicity (Harmful), Respiratory Sensitizer'),
(UUID(),'Tin (II) Chlorid Dihydrate (PA)', 'Respiratory Sensitizer, Specific Target Organ Systemic Toxicity (STOST),Corrosives, Irritant, Dermal Sensitizer, Acute Toxicity (Harmful), Environmental Toxicity'),
(UUID(),'Trichloro Acetic Acid', 'Corrosives, Irritant, Dermal Sensitizer, Acute Toxicity (Harmful), Environmental Toxicity'),
(UUID(),'Tri-Natrium Phospat (PA)', 'Irritant, Dermal Sensitizer, Acute Toxicity (Harmful)'),
(UUID(),'Xylene (Teknis)', 'Flammables, Respiratory Sensitizer, Specific Target Organ Systemic Toxicity (STOST), Irritant, Dermal Sensitizer, Acute Toxicity (Harmful)'),
(UUID(),'Zinc Oxide (PA)', 'Environmental Toxicity'),
(UUID(),'Zinn (II) Chlorid Di-Hydrat (PA)', 'Respiratory Sensitizer, Specific Target Organ Systemic Toxicity (STOST),Corrosives, Irritant, Dermal Sensitizer, Acute Toxicity (Harmful), Environmental Toxicity'),
(UUID(),'Zinn Pulfer', 'Environmental Toxicity');